version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: thexeoai  # Matches the database name in app.py
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=thexeoai  # Matches the database name in app.py
    depends_on:
      - db

volumes:
  dbdata:
