version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword  # This should match what's in app.py
      MYSQL_DATABASE: thexeoai  # New database name
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=thexeoai  # Updated to match the new database name
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db

volumes:
  dbdata:
